import Head from 'next/head'
import styles from '../styles/Home.module.css'
import GeneratePDF from '../components/GeneratePDF'

export default function Home({ people }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next JS Convert HTML to PDF
        </h1>
        <div>
          <ul>
            {people.map(({ name }, i) => (
              <li key={i}>
                { name }
              </li>
            ))}
          </ul>
        </div>
        <GeneratePDF person={ people } />
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch('http://localhost:3000/api/people')
  const people = await res.json()

  return {
    props: {
      people
    }
  }
}
